spring:
  datasource:
    url: jdbc:mysql://${SERVER_IP:127.0.0.1}:${MYSQL_PORT:3306}/u2vd?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
